server:
  port: 11111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chenchen

logging:
  charset:
    file: UTF-8
  level:
    root: info
  file:
    path: log/